### ISSUE TITLE
Unauthenticated Timeseries Ingest Node

### ISSUE THREAD

**Issue by jcrockercf** [SenseTecnic/node-red-contrib-predix-timeseries#1]
I have a basic nod red flow where I inject the sample JSON input provided in your "read.me". When I deploy the flow, I see a "302: Found" message printed to the debug tab of node red. Upon trying to inject the JSON into the timeseries ingest node, I get "Websocket not connected" in the debug tab. I understand that for some reason I am failing to authenticate with the Predix timeseries service, but after double checking all the connection parameters required for the node, I am not sure how to further debug this. Any suggestions would be very much appreciated!

Thank you!

Injected JSON: 

`{       "messageId": "1453338376222",       "body": [         {           "name": "Compressor-2015:CompressionRatio",           "datapoints": [             [               1453338376222,               10,               3             ],             [               1453338377222,               10,               1             ]           ],           "attributes": {             "host": "server1",             "customer": "Acme"           }         }       ]     }  `

The flow:
![image](https://cloud.githubusercontent.com/assets/22683315/20228916/9903657e-a821-11e6-9fd0-2bfdffbd367d.png)

Node Red Debug tab:
![image](https://cloud.githubusercontent.com/assets/22683315/20229024/3229bcf8-a822-11e6-86b4-f90832d00f13.png)

**Comment by jmikerq** [comment]
hello jcrockercf, first thing I would check is the information in the timeseries client config and your setup on predix timeseries. You can refer to our quick setup guide file in the repo to check your setup on predix. If you have all the correct setting, the ingest node should show "Authenticated" when you deploy the node.

**Comment by jmikerq** [comment]
hello @jcrockercf , I just have this issue replicated on my end right now. 

The trick is to include "/oauth/token" at the end of the UAA url. You are probably hitting the wrong UAA address when you set up the client config. I will update the document on this.

**Comment by jcrockercf** [comment]
@jmikerq Thank you for your quick replies and suggestion! I made addition of "/oauth/token" to the url and it worked. Thank you very much!

**Comment by jmikerq** [comment]
The next rev will correct this error by checking the address and automatically add "/oauth/token" to the end of the UAA url if needed.
